---
  Instances: {}
  Data:
    Logs:
      type:
        debug: true
        info: true
        notice: true
        warning: true
        error: true
        critical: true
        emergency: true
      output:
        default: "console"
